import os


MILVUS_USER = os.getenv("MILVUS_USER", "alpha")
MILVUS_PASSWORD = os.getenv("MILVUS_PASSWORD", "developer")
MILVUS_HOST = os.getenv("MILVUS_HOST", "127.0.0.1")
MILVUS_PORT = os.getenv("MILVUS_PORT", "19530")
MILVUS_COLLECTION = os.getenv("MILVUS_COLLECTION", "test")
MILVUS_DIMENSION = os.getenv("MILVUS_DIMENSION", 128)
MILVUS_INDEX_FILE_SIZE = os.getenv("MILVUS_INDEX_FILE_SIZE", 1024)
MILVUS_METRIC_TYPE = os.getenv("MILVUS_METRIC_TYPE", "L2")
MILVUS_INDEX_TYPE = os.getenv("MILVUS_INDEX_TYPE", "IVF_FLAT")
MILVUS_NLIST = os.getenv("MILVUS_NLIST", 16384)
MILVUS_TOP_K = os.getenv("MILVUS_TOP_K", 10)
MILVUS_SEARCH_PARAM = {"nprobe": 16}
MILVUS_TIMEOUT = 60
MILVUS_SEARCH_TIMEOUT = 60
MILVUS_INSERT_TIMEOUT = 60
MILVUS_UPSERT_TIMEOUT = 60
MILVUS_CREATE_TIMEOUT = 60
MILVUS_DROP_TIMEOUT = 60
MILVUS_HAS_TIMEOUT = 60
MILVUS_DELETE_TIMEOUT = 60
MILVUS_LOAD_TIMEOUT = 60
MILVUS_RELEASE_TIMEOUT = 60
MILVUS_FLUSH_TIMEOUT = 60
MILVUS_COMPACT_TIMEOUT = 60
MILVUS_GET_TIMEOUT = 60
MILVUS_COUNT_TIMEOUT = 60
MILVUS_GET_PARTITION_STATS_TIMEOUT = 60
MILVUS_GET_COLLECTION_STATS_TIMEOUT = 60
MILVUS_CALCULATE_DISTANCE_TIMEOUT = 60